stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
  rules:
    # Scan changed files in MRs, (diff-aware scanning):
    - if: $CI_MERGE_REQUEST_IID
    # Scan mainline (default) branches and report all findings.
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

semgrep:
  image: returntocorp/semgrep
  before_script:
    - apk add openjdk17
    - java --version
    - apk add maven
    - mvn --version
    - mvn dependency:tree $MAVEN_CLI_OPTS -DoutputFile=maven_dep_tree.txt
  script: semgrep ci
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    GITLAB_TOKEN: $PAT
    SEMGREP_APP_TOKEN: $SEMGREP_APP_TOKEN
    SEMGREP_JOB_URL: $CI_JOB_URL
    SEMGREP_COMMIT: $CI_COMMIT_SHA
    SEMGREP_BRANCH: $CI_COMMIT_REF_NAME
    SEMGREP_REPO_NAME: $CI_PROJECT_NAME
    SEMGREP_REPO_URL: $CI_REPOSITORY_URL
    SEMGREP_PR_ID: $CI_MERGE_REQUEST_ID